spring.application.name=Trading

server.port=5454

spring.data.mongodb.uri=your_mongodb_database_string_here

stripe.api.key=your_stripe_api_key_here
razorpay.api.key=your_razorpay_api_key_here
razorpay.api.secret=your_razorpay_api_secret_here
