spring.application.name=Trading

server.port=5454

spring.data.mongodb.uri=mongodb+srv://i4399242_db_user:47HwB8BttQWWyblz@cluster0.q3yoykn.mongodb.net/trading

stripe.api.key=your_stripe_api_key_here
razorpay.api.key=your_razorpay_api_key_here
razorpay.api.secret=your_razorpay_api_secret_here
